title: Scarllet Karen Ortega Rojas
logo: /assets/img/assets/Scarllet.jpg

description: >
Second year PhD student in Physical Sciences at the Universidad de Concepci√≥n, under the supervision of Dr. Leonardo Krapp. My research interests include the interstellar medium, stellar clusters, and numerical simulations.
 <br><br>

theme: jekyll-theme-minimal
