title: Scarllet Karen Ortega Rojas
logo: /assets/img/assets/Scarllet.jpg

description: >
 Second-year PhD student in Physical Sciences at Universidad de Concepci√≥n, supervised by Dr. Leonardo Krapp. Research interests include the interstellar medium, stellar clusters, and numerical simulations.

theme: jekyll-theme-minimal
